## SegFormer-based segmentation under data corruption

This notebook runs segmentation experiments using the SegFormer
architecture across different data corruption levels and configurations.
The objective is to analyze the robustness of a transformer-based semantic
segmentation model when trained and evaluated on corrupted SAR data.

The notebook covers model setup, training, and inference for each
corruption setting, and saves the resulting segmentation outputs for
downstream qualitative and quantitative comparison.

In [7]:
import torch
import numpy as np
from datasets import Dataset, Image
# from torch.utils.data import Dataset, DataLoader, random_split
from transformers import SegformerForSemanticSegmentation, SegformerImageProcessor, TrainingArguments, Trainer
from PIL import Image as PILImage
from sklearn.model_selection import train_test_split
import evaluate
import glob
import torch.nn as nn
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device_type = "cuda" if torch.cuda.is_available() else "cpu"

IMAGE_SIZE = (512, 512)  # Resize images to this size
BATCH_SIZE = 4
NUM_EPOCHS = 50
LEARNING_RATE = 5e-5
VAL_SPLIT = 0.125

id2label = {0: 'background', 1: 'water'}
label2id = {label: id for id, label in id2label.items()}
NUM_CLASSES = len(id2label)

MODEL_CHECKPOINT = 'nvidia/mit-b4'
processor = SegformerImageProcessor.from_pretrained(MODEL_CHECKPOINT)

metric = evaluate.load('mean_iou')

c:\Users\ADMIN\anaconda3\envs\tf_gpu\lib\site-packages\transformers\utils\deprecation.py:172: UserWarning: The following named arguments are not valid for `SegformerImageProcessor.__init__` and were ignored: 'feature_extractor_type'
  return func(*args, **kwargs)

In [8]:
def load_image_as_rgb(image_path):
    # Open image
    img = PILImage.open(image_path)
    
    # If the image is grayscale (mode 'L'), convert it to RGB
    if img.mode == 'L':
        img = img.convert('RGB')  # Convert grayscale to RGB
    return img

def load_mask_as_binary(mask_path):
    # Open mask image (keep it in grayscale)
    mask = PILImage.open(mask_path)

    # Convert to grayscale (if not already in mode 'L')
    if mask.mode != 'L':
        mask = mask.convert('L')
    
    # Convert mask values from 0-255 to 0-1 (binary)
    mask = np.array(mask)  # Convert to NumPy array
    mask[mask == 255] = 1   # Replace 255 with 1
    mask[mask == 0] = 0     # Ensure 0 stays as 0
    
    # Convert back to PIL Image for compatibility
    mask = PILImage.fromarray(mask)
    
    return mask

def create_dataset(image_paths, mask_paths):
    # Apply the custom loader for RGB images and grayscale masks
    image_paths_rgb = [load_image_as_rgb(img_path) for img_path in image_paths]
    mask_paths_gray = [load_mask_as_binary(mask_path) for mask_path in mask_paths]
    
    # Create dataset from image paths and mask paths
    dataset = Dataset.from_dict({'pixel_values': image_paths_rgb,
                                 'label': mask_paths_gray})
    
    # Ensure images are loaded as Image() format (from PIL images)
    dataset = dataset.cast_column('pixel_values', Image())
    dataset = dataset.cast_column('label', Image())  # Keep masks as grayscale images
    return dataset


def apply_transforms(batch):
    images = [x for x in batch['pixel_values']]
    labels = [x for x in batch['label']]
    
    # Convert PIL images to NumPy arrays for processing
    images = [np.array(image) for image in images]
    labels = [np.array(label) for label in labels]
    
    # print(labels)    

    inputs = processor(images, labels)
    return inputs

def get_train_datasets(train_image_dir, train_mask_dir):
    
    images = sorted(glob.glob(os.path.join(train_image_dir, "*.png")))
    masks = sorted(glob.glob(os.path.join(train_mask_dir, "*.png")))
    
    print(images)
    print(masks)

    print(f'{len(images)} images detected.')

    train_images, val_images, train_masks, val_masks = train_test_split(
        images, masks, test_size=VAL_SPLIT, random_state=0, shuffle=True)

    print(f'Train images: {len(train_images)}\nValidation images: {len(val_images)}')
    
    # Usage
    ds_train = create_dataset(train_images, train_masks)
    ds_valid = create_dataset(val_images, val_masks)

    ds_train.set_transform(apply_transforms)
    ds_valid.set_transform(apply_transforms)
    
    return ds_train, ds_valid

def compute_metrics(eval_pred):
    with torch.no_grad():
        logits, labels = eval_pred
        # print(labels.shape[-2:])
        logits_tensor = torch.from_numpy(logits)
        # scale the logits to the size of the label
        logits_tensor = nn.functional.interpolate(
            logits_tensor,
            size=labels.shape[-2:],
            mode='bilinear',
            align_corners=False,
        ).argmax(dim=1)

        pred_labels = logits_tensor.detach().cpu().numpy()
        # currently using _compute instead of compute
        # see this issue for more info: https://github.com/huggingface/evaluate/pull/328#issuecomment-1286866576
        metrics = metric._compute(
                predictions=pred_labels,
                references=labels,
                num_labels=len(id2label),
                ignore_index=None,
                reduce_labels=processor.do_reduce_labels,
            )

        # add per category metrics as individual key-value pairs
        per_category_accuracy = metrics.pop("per_category_accuracy").tolist()
        per_category_iou = metrics.pop("per_category_iou").tolist()

        metrics.update({f"accuracy_{id2label[i]}": v for i, v in enumerate(per_category_accuracy)})
        metrics.update({f"iou_{id2label[i]}": v for i, v in enumerate(per_category_iou)})

        return metrics

In [ ]:
corruptions = [2,12,15,17,20,25,30]

for corruption in corruptions:
    
    train_image_dir = "./sar_images/images/train"
    train_mask_dir = f"./sar_images/masks/train_{corruption}"
    save_path = f"segformer_water_{corruption}"
    save_path_temp = f"segformer_water_finetuned_{corruption}"
    
    print("Corruption: " + str(corruption))

    model = SegformerForSemanticSegmentation.from_pretrained(
        MODEL_CHECKPOINT,
        num_labels=NUM_CLASSES,
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True,
    )
    
    model.to(device)
    
    ds_train, ds_valid = get_train_datasets(train_image_dir, train_mask_dir)
    
    training_args = TrainingArguments(
        output_dir=save_path_temp,
        learning_rate=LEARNING_RATE,
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        save_total_limit=3,
        # eval_strategy='steps',
        save_strategy='epoch',
        eval_strategy='epoch',
        logging_strategy='epoch',
        # save_steps=20,
        # eval_steps=20,
        logging_steps=1,
        eval_accumulation_steps=5,
        load_best_model_at_end=True,
        push_to_hub=False,
        report_to='none'
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=ds_train,
        eval_dataset=ds_valid,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    model.save_pretrained(save_path)

Corruption: 2

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 12

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 15

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 17

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 20

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 25

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra

Corruption: 30

Some weights of SegformerForSemanticSegmentation were not initialized from the model checkpoint at nvidia/mit-b4 and are newly initialized: ['decode_head.batch_norm.bias', 'decode_head.batch_norm.num_batches_tracked', 'decode_head.batch_norm.running_mean', 'decode_head.batch_norm.running_var', 'decode_head.batch_norm.weight', 'decode_head.classifier.bias', 'decode_head.classifier.weight', 'decode_head.linear_c.0.proj.bias', 'decode_head.linear_c.0.proj.weight', 'decode_head.linear_c.1.proj.bias', 'decode_head.linear_c.1.proj.weight', 'decode_head.linear_c.2.proj.bias', 'decode_head.linear_c.2.proj.weight', 'decode_head.linear_c.3.proj.bias', 'decode_head.linear_c.3.proj.weight', 'decode_head.linear_fuse.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

['./sar_images/images/train\\0.png', './sar_images/images/train\\1.png', './sar_images/images/train\\100.png', './sar_images/images/train\\1000.png', './sar_images/images/train\\1001.png', './sar_images/images/train\\1002.png', './sar_images/images/train\\1003.png', './sar_images/images/train\\1004.png', './sar_images/images/train\\1005.png', './sar_images/images/train\\1006.png', './sar_images/images/train\\1007.png', './sar_images/images/train\\1009.png', './sar_images/images/train\\101.png', './sar_images/images/train\\1011.png', './sar_images/images/train\\1013.png', './sar_images/images/train\\1014.png', './sar_images/images/train\\1015.png', './sar_images/images/train\\1016.png', './sar_images/images/train\\1017.png', './sar_images/images/train\\1018.png', './sar_images/images/train\\1019.png', './sar_images/images/train\\102.png', './sar_images/images/train\\1021.png', './sar_images/images/train\\1022.png', './sar_images/images/train\\1023.png', './sar_images/images/train\\1024.png', './sar_images/images/train\\1026.png', './sar_images/images/train\\1027.png', './sar_images/images/train\\1029.png', './sar_images/images/train\\103.png', './sar_images/images/train\\1032.png', './sar_images/images/train\\1033.png', './sar_images/images/train\\1034.png', './sar_images/images/train\\1036.png', './sar_images/images/train\\1038.png', './sar_images/images/train\\1039.png', './sar_images/images/train\\104.png', './sar_images/images/train\\1040.png', './sar_images/images/train\\1042.png', './sar_images/images/train\\1045.png', './sar_images/images/train\\1046.png', './sar_images/images/train\\1047.png', './sar_images/images/train\\1049.png', './sar_images/images/train\\105.png', './sar_images/images/train\\1050.png', './sar_images/images/train\\1051.png', './sar_images/images/train\\1052.png', './sar_images/images/train\\1053.png', './sar_images/images/train\\1054.png', './sar_images/images/train\\1055.png', './sar_images/images/train\\1056.png', './sar_images/images/train\\1057.png', './sar_images/images/train\\1059.png', './sar_images/images/train\\1062.png', './sar_images/images/train\\1063.png', './sar_images/images/train\\1064.png', './sar_images/images/train\\1065.png', './sar_images/images/train\\1066.png', './sar_images/images/train\\1067.png', './sar_images/images/train\\1068.png', './sar_images/images/train\\1069.png', './sar_images/images/train\\107.png', './sar_images/images/train\\1070.png', './sar_images/images/train\\1071.png', './sar_images/images/train\\1072.png', './sar_images/images/train\\1074.png', './sar_images/images/train\\1076.png', './sar_images/images/train\\1077.png', './sar_images/images/train\\1078.png', './sar_images/images/train\\108.png', './sar_images/images/train\\1080.png', './sar_images/images/train\\1081.png', './sar_images/images/train\\1082.png', './sar_images/images/train\\1083.png', './sar_images/images/train\\1084.png', './sar_images/images/train\\1085.png', './sar_images/images/train\\1087.png', './sar_images/images/train\\1088.png', './sar_images/images/train\\1089.png', './sar_images/images/train\\109.png', './sar_images/images/train\\1090.png', './sar_images/images/train\\1091.png', './sar_images/images/train\\1092.png', './sar_images/images/train\\1093.png', './sar_images/images/train\\1095.png', './sar_images/images/train\\1096.png', './sar_images/images/train\\1097.png', './sar_images/images/train\\1098.png', './sar_images/images/train\\1099.png', './sar_images/images/train\\11.png', './sar_images/images/train\\110.png', './sar_images/images/train\\1100.png', './sar_images/images/train\\1101.png', './sar_images/images/train\\1102.png', './sar_images/images/train\\1104.png', './sar_images/images/train\\1105.png', './sar_images/images/train\\1106.png', './sar_images/images/train\\1107.png', './sar_images/images/train\\1108.png', './sar_images/images/train\\1109.png', './sar_images/images/train\\111.png', './sar_images/images/train\\1110.png', './sar_images/images/train\\1111.png', './sar_images/images/train\\1112.png', './sar_images/images/train\\1113.png', './sar_images/images/train\\1115.png', './sar_images/images/train\\1116.png', './sar_images/images/train\\1117.png', './sar_images/images/train\\1118.png', './sar_images/images/train\\112.png', './sar_images/images/train\\1120.png', './sar_images/images/train\\1121.png', './sar_images/images/train\\1122.png', './sar_images/images/train\\1123.png', './sar_images/images/train\\1125.png', './sar_images/images/train\\1126.png', './sar_images/images/train\\1127.png', './sar_images/images/train\\1128.png', './sar_images/images/train\\1129.png', './sar_images/images/train\\113.png', './sar_images/images/train\\1132.png', './sar_images/images/train\\1133.png', './sar_images/images/train\\1134.png', './sar_images/images/train\\1135.png', './sar_images/images/train\\1136.png', './sar_images/images/train\\1137.png', './sar_images/images/train\\1138.png', './sar_images/images/train\\114.png', './sar_images/images/train\\1140.png', './sar_images/images/train\\1141.png', './sar_images/images/train\\1143.png', './sar_images/images/train\\1144.png', './sar_images/images/train\\1145.png', './sar_images/images/train\\1146.png', './sar_images/images/train\\1147.png', './sar_images/images/train\\1148.png', './sar_images/images/train\\115.png', './sar_images/images/train\\1150.png', './sar_images/images/train\\1151.png', './sar_images/images/train\\1152.png', './sar_images/images/train\\1153.png', './sar_images/images/train\\1154.png', './sar_images/images/train\\1155.png', './sar_images/images/train\\1156.png', './sar_images/images/train\\1157.png', './sar_images/images/train\\1158.png', './sar_images/images/train\\1159.png', './sar_images/images/train\\116.png', './sar_images/images/train\\1162.png', './sar_images/images/train\\1163.png', './sar_images/images/train\\1166.png', './sar_images/images/train\\1167.png', './sar_images/images/train\\1169.png', './sar_images/images/train\\1171.png', './sar_images/images/train\\1172.png', './sar_images/images/train\\1173.png', './sar_images/images/train\\1174.png', './sar_images/images/train\\1175.png', './sar_images/images/train\\1176.png', './sar_images/images/train\\1177.png', './sar_images/images/train\\1179.png', './sar_images/images/train\\118.png', './sar_images/images/train\\1182.png', './sar_images/images/train\\1183.png', './sar_images/images/train\\1184.png', './sar_images/images/train\\1185.png', './sar_images/images/train\\1186.png', './sar_images/images/train\\1189.png', './sar_images/images/train\\1190.png', './sar_images/images/train\\1191.png', './sar_images/images/train\\1192.png', './sar_images/images/train\\1193.png', './sar_images/images/train\\1194.png', './sar_images/images/train\\1195.png', './sar_images/images/train\\1196.png', './sar_images/images/train\\1197.png', './sar_images/images/train\\1199.png', './sar_images/images/train\\12.png', './sar_images/images/train\\1200.png', './sar_images/images/train\\1201.png', './sar_images/images/train\\1202.png', './sar_images/images/train\\1203.png', './sar_images/images/train\\1204.png', './sar_images/images/train\\1205.png', './sar_images/images/train\\1206.png', './sar_images/images/train\\1207.png', './sar_images/images/train\\1208.png', './sar_images/images/train\\1209.png', './sar_images/images/train\\1210.png', './sar_images/images/train\\1211.png', './sar_images/images/train\\1212.png', './sar_images/images/train\\1213.png', './sar_images/images/train\\1214.png', './sar_images/images/train\\1215.png', './sar_images/images/train\\1216.png', './sar_images/images/train\\1217.png', './sar_images/images/train\\1218.png', './sar_images/images/train\\122.png', './sar_images/images/train\\1220.png', './sar_images/images/train\\1221.png', './sar_images/images/train\\1223.png', './sar_images/images/train\\1224.png', './sar_images/images/train\\1225.png', './sar_images/images/train\\1226.png', './sar_images/images/train\\1227.png', './sar_images/images/train\\1228.png', './sar_images/images/train\\1229.png', './sar_images/images/train\\123.png', './sar_images/images/train\\1230.png', './sar_images/images/train\\1231.png', './sar_images/images/train\\1233.png', './sar_images/images/train\\1234.png', './sar_images/images/train\\1235.png', './sar_images/images/train\\1236.png', './sar_images/images/train\\1238.png', './sar_images/images/train\\124.png', './sar_images/images/train\\1240.png', './sar_images/images/train\\1241.png', './sar_images/images/train\\1242.png', './sar_images/images/train\\1243.png', './sar_images/images/train\\1244.png', './sar_images/images/train\\1245.png', './sar_images/images/train\\1246.png', './sar_images/images/train\\1247.png', './sar_images/images/train\\1248.png', './sar_images/images/train\\1249.png', './sar_images/images/train\\1250.png', './sar_images/images/train\\1251.png', './sar_images/images/train\\1253.png', './sar_images/images/train\\1254.png', './sar_images/images/train\\1255.png', './sar_images/images/train\\1256.png', './sar_images/images/train\\1257.png', './sar_images/images/train\\1258.png', './sar_images/images/train\\1259.png', './sar_images/images/train\\126.png', './sar_images/images/train\\1260.png', './sar_images/images/train\\1261.png', './sar_images/images/train\\127.png', './sar_images/images/train\\128.png', './sar_images/images/train\\13.png', './sar_images/images/train\\130.png', './sar_images/images/train\\131.png', './sar_images/images/train\\132.png', './sar_images/images/train\\134.png', './sar_images/images/train\\135.png', './sar_images/images/train\\136.png', './sar_images/images/train\\137.png', './sar_images/images/train\\138.png', './sar_images/images/train\\14.png', './sar_images/images/train\\140.png', './sar_images/images/train\\141.png', './sar_images/images/train\\142.png', './sar_images/images/train\\144.png', './sar_images/images/train\\145.png', './sar_images/images/train\\146.png', './sar_images/images/train\\147.png', './sar_images/images/train\\148.png', './sar_images/images/train\\149.png', './sar_images/images/train\\150.png', './sar_images/images/train\\152.png', './sar_images/images/train\\153.png', './sar_images/images/train\\155.png', './sar_images/images/train\\156.png', './sar_images/images/train\\157.png', './sar_images/images/train\\158.png', './sar_images/images/train\\159.png', './sar_images/images/train\\16.png', './sar_images/images/train\\160.png', './sar_images/images/train\\161.png', './sar_images/images/train\\162.png', './sar_images/images/train\\163.png', './sar_images/images/train\\165.png', './sar_images/images/train\\166.png', './sar_images/images/train\\167.png', './sar_images/images/train\\168.png', './sar_images/images/train\\169.png', './sar_images/images/train\\17.png', './sar_images/images/train\\170.png', './sar_images/images/train\\171.png', './sar_images/images/train\\172.png', './sar_images/images/train\\173.png', './sar_images/images/train\\174.png', './sar_images/images/train\\175.png', './sar_images/images/train\\176.png', './sar_images/images/train\\177.png', './sar_images/images/train\\178.png', './sar_images/images/train\\179.png', './sar_images/images/train\\18.png', './sar_images/images/train\\182.png', './sar_images/images/train\\183.png', './sar_images/images/train\\185.png', './sar_images/images/train\\186.png', './sar_images/images/train\\19.png', './sar_images/images/train\\190.png', './sar_images/images/train\\191.png', './sar_images/images/train\\192.png', './sar_images/images/train\\194.png', './sar_images/images/train\\196.png', './sar_images/images/train\\198.png', './sar_images/images/train\\199.png', './sar_images/images/train\\2.png', './sar_images/images/train\\200.png', './sar_images/images/train\\202.png', './sar_images/images/train\\206.png', './sar_images/images/train\\207.png', './sar_images/images/train\\208.png', './sar_images/images/train\\209.png', './sar_images/images/train\\210.png', './sar_images/images/train\\212.png', './sar_images/images/train\\213.png', './sar_images/images/train\\215.png', './sar_images/images/train\\218.png', './sar_images/images/train\\219.png', './sar_images/images/train\\22.png', './sar_images/images/train\\220.png', './sar_images/images/train\\223.png', './sar_images/images/train\\224.png', './sar_images/images/train\\225.png', './sar_images/images/train\\226.png', './sar_images/images/train\\227.png', './sar_images/images/train\\228.png', './sar_images/images/train\\229.png', './sar_images/images/train\\23.png', './sar_images/images/train\\230.png', './sar_images/images/train\\231.png', './sar_images/images/train\\232.png', './sar_images/images/train\\233.png', './sar_images/images/train\\234.png', './sar_images/images/train\\235.png', './sar_images/images/train\\237.png', './sar_images/images/train\\238.png', './sar_images/images/train\\239.png', './sar_images/images/train\\24.png', './sar_images/images/train\\240.png', './sar_images/images/train\\241.png', './sar_images/images/train\\244.png', './sar_images/images/train\\245.png', './sar_images/images/train\\246.png', './sar_images/images/train\\247.png', './sar_images/images/train\\249.png', './sar_images/images/train\\25.png', './sar_images/images/train\\250.png', './sar_images/images/train\\252.png', './sar_images/images/train\\253.png', './sar_images/images/train\\255.png', './sar_images/images/train\\256.png', './sar_images/images/train\\257.png', './sar_images/images/train\\258.png', './sar_images/images/train\\26.png', './sar_images/images/train\\260.png', './sar_images/images/train\\261.png', './sar_images/images/train\\262.png', './sar_images/images/train\\264.png', './sar_images/images/train\\265.png', './sar_images/images/train\\266.png', './sar_images/images/train\\267.png', './sar_images/images/train\\268.png', './sar_images/images/train\\269.png', './sar_images/images/train\\27.png', './sar_images/images/train\\270.png', './sar_images/images/train\\272.png', './sar_images/images/train\\275.png', './sar_images/images/train\\276.png', './sar_images/images/train\\277.png', './sar_images/images/train\\28.png', './sar_images/images/train\\280.png', './sar_images/images/train\\281.png', './sar_images/images/train\\282.png', './sar_images/images/train\\284.png', './sar_images/images/train\\286.png', './sar_images/images/train\\287.png', './sar_images/images/train\\288.png', './sar_images/images/train\\289.png', './sar_images/images/train\\290.png', './sar_images/images/train\\291.png', './sar_images/images/train\\292.png', './sar_images/images/train\\293.png', './sar_images/images/train\\295.png', './sar_images/images/train\\296.png', './sar_images/images/train\\297.png', './sar_images/images/train\\298.png', './sar_images/images/train\\299.png', './sar_images/images/train\\3.png', './sar_images/images/train\\30.png', './sar_images/images/train\\300.png', './sar_images/images/train\\301.png', './sar_images/images/train\\304.png', './sar_images/images/train\\307.png', './sar_images/images/train\\308.png', './sar_images/images/train\\31.png', './sar_images/images/train\\310.png', './sar_images/images/train\\311.png', './sar_images/images/train\\312.png', './sar_images/images/train\\314.png', './sar_images/images/train\\315.png', './sar_images/images/train\\316.png', './sar_images/images/train\\317.png', './sar_images/images/train\\318.png', './sar_images/images/train\\319.png', './sar_images/images/train\\32.png', './sar_images/images/train\\321.png', './sar_images/images/train\\322.png', './sar_images/images/train\\323.png', './sar_images/images/train\\324.png', './sar_images/images/train\\326.png', './sar_images/images/train\\328.png', './sar_images/images/train\\33.png', './sar_images/images/train\\330.png', './sar_images/images/train\\331.png', './sar_images/images/train\\332.png', './sar_images/images/train\\333.png', './sar_images/images/train\\336.png', './sar_images/images/train\\337.png', './sar_images/images/train\\338.png', './sar_images/images/train\\339.png', './sar_images/images/train\\34.png', './sar_images/images/train\\341.png', './sar_images/images/train\\342.png', './sar_images/images/train\\343.png', './sar_images/images/train\\344.png', './sar_images/images/train\\345.png', './sar_images/images/train\\347.png', './sar_images/images/train\\349.png', './sar_images/images/train\\35.png', './sar_images/images/train\\350.png', './sar_images/images/train\\351.png', './sar_images/images/train\\352.png', './sar_images/images/train\\354.png', './sar_images/images/train\\355.png', './sar_images/images/train\\356.png', './sar_images/images/train\\357.png', './sar_images/images/train\\359.png', './sar_images/images/train\\36.png', './sar_images/images/train\\360.png', './sar_images/images/train\\361.png', './sar_images/images/train\\363.png', './sar_images/images/train\\364.png', './sar_images/images/train\\365.png', './sar_images/images/train\\366.png', './sar_images/images/train\\367.png', './sar_images/images/train\\369.png', './sar_images/images/train\\370.png', './sar_images/images/train\\371.png', './sar_images/images/train\\374.png', './sar_images/images/train\\375.png', './sar_images/images/train\\376.png', './sar_images/images/train\\377.png', './sar_images/images/train\\378.png', './sar_images/images/train\\379.png', './sar_images/images/train\\380.png', './sar_images/images/train\\381.png', './sar_images/images/train\\382.png', './sar_images/images/train\\383.png', './sar_images/images/train\\384.png', './sar_images/images/train\\386.png', './sar_images/images/train\\387.png', './sar_images/images/train\\388.png', './sar_images/images/train\\389.png', './sar_images/images/train\\39.png', './sar_images/images/train\\390.png', './sar_images/images/train\\391.png', './sar_images/images/train\\392.png', './sar_images/images/train\\393.png', './sar_images/images/train\\395.png', './sar_images/images/train\\396.png', './sar_images/images/train\\397.png', './sar_images/images/train\\398.png', './sar_images/images/train\\399.png', './sar_images/images/train\\4.png', './sar_images/images/train\\40.png', './sar_images/images/train\\400.png', './sar_images/images/train\\401.png', './sar_images/images/train\\402.png', './sar_images/images/train\\403.png', './sar_images/images/train\\404.png', './sar_images/images/train\\406.png', './sar_images/images/train\\407.png', './sar_images/images/train\\408.png', './sar_images/images/train\\409.png', './sar_images/images/train\\410.png', './sar_images/images/train\\411.png', './sar_images/images/train\\412.png', './sar_images/images/train\\413.png', './sar_images/images/train\\414.png', './sar_images/images/train\\415.png', './sar_images/images/train\\416.png', './sar_images/images/train\\417.png', './sar_images/images/train\\419.png', './sar_images/images/train\\42.png', './sar_images/images/train\\420.png', './sar_images/images/train\\421.png', './sar_images/images/train\\422.png', './sar_images/images/train\\423.png', './sar_images/images/train\\424.png', './sar_images/images/train\\425.png', './sar_images/images/train\\426.png', './sar_images/images/train\\427.png', './sar_images/images/train\\428.png', './sar_images/images/train\\430.png', './sar_images/images/train\\431.png', './sar_images/images/train\\432.png', './sar_images/images/train\\433.png', './sar_images/images/train\\434.png', './sar_images/images/train\\435.png', './sar_images/images/train\\436.png', './sar_images/images/train\\437.png', './sar_images/images/train\\438.png', './sar_images/images/train\\439.png', './sar_images/images/train\\442.png', './sar_images/images/train\\444.png', './sar_images/images/train\\445.png', './sar_images/images/train\\446.png', './sar_images/images/train\\448.png', './sar_images/images/train\\449.png', './sar_images/images/train\\45.png', './sar_images/images/train\\451.png', './sar_images/images/train\\452.png', './sar_images/images/train\\453.png', './sar_images/images/train\\454.png', './sar_images/images/train\\456.png', './sar_images/images/tra